/*
 * Copyright 2020 Esri
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.esri.arcgisruntime.opensourceapps.datacollection.views.popup

import android.content.Context
import android.text.Editable
import android.text.InputType
import android.util.AttributeSet
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.EditText
import android.widget.FrameLayout
import android.widget.TextView
import androidx.core.widget.doAfterTextChanged
import androidx.databinding.DataBindingUtil
import androidx.databinding.ViewDataBinding
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.esri.arcgisruntime.ArcGISRuntimeException
import com.esri.arcgisruntime.concurrent.ListenableFuture
import com.esri.arcgisruntime.data.*
import com.esri.arcgisruntime.mapping.popup.Popup
import com.esri.arcgisruntime.mapping.popup.PopupField
import com.esri.arcgisruntime.mapping.popup.PopupManager
import com.esri.arcgisruntime.opensourceapps.datacollection.BR
import com.esri.arcgisruntime.opensourceapps.datacollection.R
import com.esri.arcgisruntime.opensourceapps.datacollection.util.Logger
import com.google.android.material.snackbar.Snackbar
import kotlinx.android.synthetic.main.item_popup_row.view.*
import kotlinx.android.synthetic.main.layout_popupview.view.*
import java.text.ParseException
import java.text.SimpleDateFormat
import java.util.*
import java.util.concurrent.ExecutionException
import kotlin.collections.ArrayList

/**
 * Displays the popup attribute list in a [RecyclerView].
 */
class PopupView : FrameLayout {

    private val popupAttributeListAdapter by lazy { PopupAttributeListAdapter() }

    // List of PopupAttributes generated by iterating over all the display fields of the popup.
    private val popupAttributeList: ArrayList<PopupAttribute> by lazy {
        val fields: List<PopupField> = popupManager.displayedFields
        val popupDisplayFieldsWithValues: ArrayList<PopupAttribute> = ArrayList()
        for (field in fields) {
            popupDisplayFieldsWithValues.add(
                PopupAttribute(
                    field,
                    field.label,
                    popupManager.getFormattedValue(field),
                    popupManager.getFieldType(field),
                    popupManager.editableFields.contains(field)
                )
            )
        }
        popupDisplayFieldsWithValues
    }

    var popup: Popup? = null
        set(value) {
            field = value
            popupAttributeListAdapter.submitList(popupAttributeList)
        }

    var editMode: Boolean = false
        set(value) {
            field = value
            popupAttributeListAdapter.notifyDataSetChanged()
        }

    var saveEdit: Boolean = false
        set(value) {field = value
            if (field) {
                saveEdits()
            }
        }

    private val popupManager by lazy {
        PopupManager(context, popup)
    }

    /**
     * Constructor used when instantiating this View directly to attach it to another view programmatically.
     */
    constructor(context: Context) : super(context) {
        init(context)
    }

    /**
     * Constructor used when defining this view in an XML layout.
     */
    constructor(context: Context, attrs: AttributeSet?) : super(context, attrs) {
        init(context)
    }

    /**
     * Initializes this PopupView by inflating the layout and setting the [RecyclerView] adapter.
     */
    private fun init(context: Context) {
        inflate(context, R.layout.layout_popupview, this)
        popupRecyclerView.layoutManager = LinearLayoutManager(context)
        popupRecyclerView.adapter = popupAttributeListAdapter
    }

    /**
     * Updates and saves popup field values that have been edited by the user.
     */
    private fun saveEdits() {
        popupManager.startEditing()
        var exception: ArcGISRuntimeException?
        for (attribute in popupAttributeList) {
            if (attribute.tempValue != null && attribute.tempValue.toString() != attribute.value && attribute.isEditable) {
                exception =
                    updateValue(popupManager, attribute.field, attribute.tempValue.toString())
                if (exception != null) {
                    val fieldName: String = attribute.fieldName
                    val message =
                        "There was an error saving the feature, the value for  $fieldName is invalid"
                    showSnackbarMessage(message)
                    break
                } else {
                    // update the attribute value with the new value
                    attribute.value = attribute.tempValue.toString()
                    savePopup()
                }
            }
        }
    }

    /**
     * Shows the message in a Snackbar.
     */
    private fun showSnackbarMessage(message: String) {
        val snackbar: Snackbar = Snackbar.make(this, message, Snackbar.LENGTH_LONG)
        snackbar.show()
    }

    /**
     * Saves the popup by applying changes to the feature service.
     */
    private fun savePopup() {
        val editingErrorFuture: ListenableFuture<ArcGISRuntimeException> = popupManager.finishEditingAsync()
        editingErrorFuture.addDoneListener {
            try {
                editingErrorFuture.get()

                val feature: Feature = popupManager.popup.geoElement as Feature
                val featureTable: FeatureTable = feature.featureTable
                if (featureTable is ServiceFeatureTable) {
                    val applyEditsFuture: ListenableFuture<List<FeatureEditResult>> =
                        featureTable.applyEditsAsync()
                    applyEditsFuture.addDoneListener {
                        try {
                            val featureEditResults: List<FeatureEditResult> = applyEditsFuture.get()
                            if (checkEditResultForErrors(featureEditResults)) {
                                showSnackbarMessage("There was a problem saving the feature")
                            } else {
                                showSnackbarMessage("Feature saved successfully")
                            }

                        } catch (ie: InterruptedException) {
                            Logger.e(
                                "Exception encountered when saving popup, " + Util.getExceptionMessageAndCause(
                                    ie
                                )
                            )
                        } catch (ee: ExecutionException) {
                            Logger.e(
                                "Exception encountered when saving popup, " + Util.getExceptionMessageAndCause(
                                    ee
                                )
                            )
                        }
                    }
                }
            } catch (ie: InterruptedException) {
                Logger.e(
                    "Exception encountered when saving popup, " + Util.getExceptionMessageAndCause(
                        ie
                    )
                )
            } catch (ee: ExecutionException) {
                Logger.e(
                    "Exception encountered when saving popup, " + Util.getExceptionMessageAndCause(
                        ee
                    )
                )
            }
        }
    }

    /**
     * Checks for errors in FeatureEditResults obtained from applying edits to service feature table.
     */
    private fun checkEditResultForErrors(featureEditResults: List<FeatureEditResult>): Boolean {
        var errorEncountered = false
        for (result in featureEditResults) {
            if (result.hasCompletedWithErrors()) {
                errorEncountered = true
                break
            }
        }
        return errorEncountered
    }


    /**
     * Updates the given popup field value with the appropriately cast string value.
     *
     * @param manager - PopupManager
     * @param field   - PopupField
     * @param value   - String
     * @return - ArcGISRuntimeException if there's a problem updating the field value,
     * otherwise null.
     */
    private fun updateValue(
        manager: PopupManager,
        field: PopupField?,
        value: String?
    ): ArcGISRuntimeException? {
        var error: ArcGISRuntimeException? = null

        when (manager.getFieldType(field)) {
            Field.Type.SHORT -> error = if (value == null || value.trim { it <= ' ' }.isEmpty()) {
                manager.updateValue(null, field)
            } else {
                manager.updateValue(value.toString().toShort(), field)
            }
            Field.Type.INTEGER -> error = if (value == null || value.trim { it <= ' ' }.isEmpty()) {
                manager.updateValue(null, field)
            } else {
                manager.updateValue(value.toString().toInt(), field)
            }
            Field.Type.FLOAT -> error = if (value == null || value.trim { it <= ' ' }.isEmpty()) {
                manager.updateValue(null, field)
            } else {
                manager.updateValue(value.toString().toFloat(), field)
            }
            Field.Type.DOUBLE -> error = if (value == null || value.trim { it <= ' ' }.isEmpty()) {
                manager.updateValue(null, field)
            } else {
                manager.updateValue(value.toString().toDouble(), field)
            }
            Field.Type.DATE -> {
                val calendar = Calendar.getInstance()
                // Save any non-empty dates
                if (value!!.trim { it <= ' ' }.isNotEmpty()) {
                    try {
                        val date = SimpleDateFormat(
                            "M/dd/yy hh:m a",
                            Locale.getDefault()
                        ).parse(value)
                        calendar.timeInMillis = date.time
                        error = manager.updateValue(calendar, field)
                    } catch (e: ParseException) {
                        Logger.e("Parse Exception when converting string $value to a date.")
                    }
                }
            }
            Field.Type.TEXT -> error =
                manager.updateValue(value.toString(), field)
            else -> Logger.i("Unhandled field type: " + manager.getFieldType(field))
        }
        return error
    }

    /**
     * Represents an object comprising of Popup display field and its value.
     */
    data class PopupAttribute(
        val field: PopupField,
        val fieldName: String,
        var value: String,
        val fieldType: Field.Type,
        val isEditable: Boolean,
        var tempValue: Editable? = null
    )

    /**
     * Adapter used by PopupView to display a list of PopupAttributes in a
     * recyclerView.
     */
    private inner class PopupAttributeListAdapter :
        ListAdapter<PopupAttribute, ViewHolder>(DiffCallback()) {

        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
            val inflater = LayoutInflater.from(parent.context)
            val binding = DataBindingUtil.inflate<ViewDataBinding>(
                inflater,
                R.layout.item_popup_row,
                parent,
                false
            )
            return ViewHolder(binding)
        }

        override fun onBindViewHolder(holder: ViewHolder, position: Int) {
            val popupAttribute: PopupAttribute = getItem(position)
            holder.setViewsBehavior(popupAttribute)

            holder.bind(popupAttribute)
        }
    }

    /**
     * Callback for calculating the diff between two non-null items in a list.
     */
    private class DiffCallback : DiffUtil.ItemCallback<PopupAttribute>() {

        override fun areItemsTheSame(
            oldItem: PopupAttribute,
            newItem: PopupAttribute
        ): Boolean {
            return oldItem == newItem
        }

        override fun areContentsTheSame(
            oldItem: PopupAttribute,
            newItem: PopupAttribute
        ): Boolean {
            return oldItem.fieldName == newItem.fieldName && oldItem.value == newItem.value
        }
    }

    /**
     * The PopupAttributeListAdapter ViewHolder.
     */
    private inner class ViewHolder(private val binding: ViewDataBinding) :
        RecyclerView.ViewHolder(binding.root) {

        val popupFieldValue: TextView by lazy {
            binding.root.popupFieldValue
        }

        val popupFieldEditValue: EditText by lazy {
            binding.root.popupFieldEditValue
        }

        fun bind(
            popupAttribute: PopupAttribute
        ) {
            binding.setVariable(BR.popupAttribute, popupAttribute)
            binding.executePendingBindings()
        }

        /**
         * Toggles the view for popup field value from edittext to textview and vice-versa, given the
         * edit mode of the popupView.
         */
        fun setViewsBehavior(popupAttribute: PopupAttribute) {
            if (isEditable(popupAttribute)) {
                popupFieldEditValue.inputType = getInputType(popupAttribute.fieldType)
                popupFieldEditValue.visibility = View.VISIBLE
                popupFieldValue.visibility = View.GONE
                // here we assign and hold the values of the editable fields, entered by the user
                // in popupAttribute.tempValue
                popupFieldEditValue.doAfterTextChanged {
                    popupAttribute.tempValue = popupFieldEditValue.text}
            } else {
                popupFieldEditValue.visibility = View.GONE
                popupFieldValue.visibility = View.VISIBLE
                popupAttribute.tempValue = null
            }
        }

        /**
         * Returns whether the popup attribute is editable based on the status of popupView edit mode
         * and if the popup attribute is editable.
         */
        fun isEditable(popupAttribute: PopupAttribute): Boolean {
            return editMode && popupAttribute.isEditable
        }

        /**
         * Returns the int value representing the input type for EditText view.
         */
        private fun getInputType(fieldType: Field.Type): Int {
            return when (fieldType) {
                Field.Type.SHORT, Field.Type.INTEGER -> InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_SIGNED
                Field.Type.FLOAT, Field.Type.DOUBLE -> InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL or InputType.TYPE_NUMBER_FLAG_SIGNED
                Field.Type.DATE -> InputType.TYPE_CLASS_DATETIME or InputType.TYPE_DATETIME_VARIATION_DATE or InputType.TYPE_DATETIME_VARIATION_NORMAL
                else -> InputType.TYPE_CLASS_TEXT
            }
        }
    }

    /**
     * Helper class containing utility static methods.
     */
    private class Util {

        companion object {

            /**
             * Gets the full error message from the exception
             *
             * @param exception - Exception
             */
            fun getExceptionMessageAndCause(exception: Exception): String? {
                var message = exception.message
                if (exception.cause != null) {
                    message = message + " Cause = " + exception.cause!!.message
                    if (exception.cause is ArcGISRuntimeException) {
                        val arcGISRuntimeException =
                            exception.cause as ArcGISRuntimeException?
                        message += ", additional message: " + arcGISRuntimeException!!.additionalMessage
                    }
                }
                return message
            }
        }
    }

}
